[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "newscraper"
version = "0.1.0"
description = "NewScraper project with MCP integration"
requires-python = ">=3.10"
dependencies = [
    "httpx",
]

[tool.hatch.build.targets.wheel]
packages = ["."]